const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("\n🚀 Deploying CampusAchievement to Base Sepolia...");
  console.log("📬 Deployer address:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("💰 Deployer balance:", ethers.formatEther(balance), "ETH\n");

  const CampusAchievement = await ethers.getContractFactory("CampusAchievement");
  const contract = await CampusAchievement.deploy(deployer.address);
  await contract.waitForDeployment();

  const contractAddress = await contract.getAddress();
  console.log("✅ CampusAchievement deployed to:", contractAddress);
  console.log("🔗 BaseScan:", `https://sepolia.basescan.org/address/${contractAddress}`);
  console.log("\n");

  // Write contract address to src/config/contract.js
  const configPath = path.join(__dirname, "../src/config/contract.js");
  const abi = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "../artifacts/contracts/CampusAchievement.sol/CampusAchievement.json")
    )
  ).abi;

  const configContent = `// AUTO-GENERATED by scripts/deploy.js — DO NOT EDIT MANUALLY
// Deployed on Base Sepolia | ${new Date().toISOString()}

export const CONTRACT_ADDRESS = "${contractAddress}";
export const DEPLOYER_ADDRESS = "${deployer.address}";
export const CHAIN_ID = 84532;
export const NETWORK_NAME = "Base Sepolia";
export const EXPLORER_URL = "https://sepolia.basescan.org";

export const CONTRACT_ABI = ${JSON.stringify(abi, null, 2)};
`;

  fs.writeFileSync(configPath, configContent);
  console.log("📝 Contract config written to src/config/contract.js");
  console.log("\n⚡ Next step: Update VITE_CONTRACT_ADDRESS in .env.local");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Deployment failed:", error);
    process.exit(1);
  });
